version: '3'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - INVITE_CODE=${INVITE_CODE}
      - MODEL_INTERVIEWER=${MODEL_INTERVIEWER}
      - MODEL_ANALYST=${MODEL_ANALYST}
      - MODEL_ARCHITECT=${MODEL_ARCHITECT}
      - MODEL_SUMMARY=${MODEL_SUMMARY}
      - MODEL_JUDGE=${MODEL_JUDGE}
      - REASONING_EFFORT_INTERVIEWER=${REASONING_EFFORT_INTERVIEWER}
      - REASONING_EFFORT_ANALYST=${REASONING_EFFORT_ANALYST}
      - REASONING_EFFORT_ARCHITECT=${REASONING_EFFORT_ARCHITECT}
      - REASONING_EFFORT_SUMMARY=${REASONING_EFFORT_SUMMARY}
      - REASONING_EFFORT_JUDGE=${REASONING_EFFORT_JUDGE}
      - TEMPERATURE_INTERVIEWER=${TEMPERATURE_INTERVIEWER}
      - TEMPERATURE_ANALYST=${TEMPERATURE_ANALYST}
      - TEMPERATURE_ARCHITECT=${TEMPERATURE_ARCHITECT}
      - TEMPERATURE_SUMMARY=${TEMPERATURE_SUMMARY}
      - TEMPERATURE_JUDGE=${TEMPERATURE_JUDGE}
      - TOP_P_INTERVIEWER=${TOP_P_INTERVIEWER}
      - TOP_P_ANALYST=${TOP_P_ANALYST}
      - TOP_P_ARCHITECT=${TOP_P_ARCHITECT}
      - TOP_P_SUMMARY=${TOP_P_SUMMARY}
      - TOP_P_JUDGE=${TOP_P_JUDGE}
      - MAX_TOKENS_INTERVIEWER=${MAX_TOKENS_INTERVIEWER}
      - MAX_TOKENS_ANALYST=${MAX_TOKENS_ANALYST}
      - MAX_TOKENS_ARCHITECT=${MAX_TOKENS_ARCHITECT}
      - MAX_TOKENS_SUMMARY=${MAX_TOKENS_SUMMARY}
      - MAX_TOKENS_JUDGE=${MAX_TOKENS_JUDGE}
      - RESPONSE_FORMAT_ANALYST=${RESPONSE_FORMAT_ANALYST}
      - RESPONSE_FORMAT_JUDGE=${RESPONSE_FORMAT_JUDGE}
